add auto_recover to new cob_helper_tools pkg
4am-robotics/cob_command_tools pull request #175
Opened 2017-01-30 15:20 UTC by ipa-fxm

@ipa-jba @ipa-mig @ipa-fmw 
How do you like this?
Related to https://github.com/ipa320/ipa_navigation_common/pull/90

I took msh-version and made it configurable via rosparam. You can use it like:
```
<?xml version="1.0" ?>
<launch>
  <node pkg="cob_helper_tools" type="auto_recover.py" name="auto_recover" output="screen">
    <param name="components" value="['base', 'torso']" />
  </node>
</launch>
```

Please comment in case something from navigation-version is not covered by this script!
Also, we might want to consider other scripts from msh to this new package for more prominent usage...

2017-01-31 07:36 UTC, mgruhler reviewed
looks good to me.

What is the difference between the em state recover and the diagnostics recover?

I figure that the former happens automatically after an em stop has been released. But what about the latter? When does this occur?

2017-01-31 07:36 UTC, ipa-mig commented on cob_helper_tools/scripts/auto_recover.py
> +
maybe we should start again to put [the headers](https://github.com/ipa320/setup/tree/master/templates) in our sourcefiles.

2017-01-31 09:40 UTC, ipa-fxm commented
I guess the second comes from recoverable hardware failures...:wink:

2017-01-31 10:49 UTC, ipa-fmw commented on cob_helper_tools/scripts/auto_recover.py
> +
+1

2017-01-31 10:49 UTC, floweisshardt approved these changes

2017-01-31 10:50 UTC, ipa-fmw commented
anoter script which would fit in here is `auto_init.py`

2017-02-02 15:05 UTC, ipa-flg commented
@ipa-fxm :top:

2017-02-02 15:26 UTC, mgruhler requested changes
enforcing license headers :-)

2017-02-03 08:37 UTC, ipa-flg commented
@ipa-fxm <rosparam param="components">[base]</rosparam>

2017-02-03 08:53 UTC, ipa-flg commented
@ipa-fxm tested auto_init and auto_recover on raw3-3, both working fine :+1:

2017-02-03 09:16 UTC, ipa-fxm commented
@ipa-mig 
Done license header...please approve and merge!

2017-02-03 09:30 UTC, mgruhler approved these changes

2017-02-03 09:30 UTC, merged