Feature/generic throttle
4am-robotics/cob_command_tools pull request #193
Opened 2017-06-30 14:39 UTC by MattiaRacca

2017-07-03 13:48 UTC, ipa-fxm commented
Hmm, can you explain the benefit of this implementation?
How is it different from http://wiki.ros.org/topic_tools/throttle?

2017-07-03 14:21 UTC, MattiaRacca commented
Sure. First, topic_tools/throttle instantiate a node for each throttled topic while this implementation can throttle several topics because each topic has its own subscriber/publisher pair. Each throttled topic has its own pair of thread (one running the publisher at the requested rate and one for the subscriber callback.
All parameters of the generic throttle are defined through ros parameters. An example of .yaml file follows:
```
generic_throttle:
  namespace: throttled_topics
  delay: 5

  topic_framerate:
    - [/torso_cam3d_left/rgb/image_raw, 1]
    - [/torso_cam3d_right/rgb/image_raw, 1]
    - [/base/joint_states, 1]
```
Second, the standard behaviour of the generic_throttle is to latch for a certain "delay" the last message if no new message become available. After "delay" seconds, the throttle will stop publishing the old message and wait for new messages to become available. This degree of control is not possible with topic_tools/throttle that is implemented with a simple dequeue. Although now it is the default (required by  @ipa-fmw ), the latched behaviour could be made optional.

Third, although it is not in this pull request, I have ready a version of the throttle that, for specific topics that publish sensor_msgs/Image, adjusts the resolution before publishing the image.

2017-07-03 17:04 UTC, fmessmer requested changes
some comments

2017-07-03 17:04 UTC, ipa-fxm commented on generic_throttle/package.xml
> +<package>
please use package format2

2017-07-03 17:04 UTC, ipa-fxm commented on generic_throttle/package.xml
> +  <run_depend>visualization_msgs</run_depend>
some of the listed dependencies are not used....please remove them

2017-07-03 17:04 UTC, ipa-fxm commented on generic_throttle/CMakeLists.txt
> +  visualization_msgs
entries only needed for c++ code...not for python....remove the ROS packages...just keep catkin...

2017-07-03 17:09 UTC, ipa-fxm commented
Thanks for the explanation

 > Second, the standard behaviour of the generic_throttle is to latch for a certain "delay" the last message if no new message become available. After "delay" seconds, the throttle will stop publishing the old message and wait for new messages to become available. This degree of control is not possible with topic_tools/throttle that is implemented with a simple dequeue. Although now it is the default (required by @ipa-fmw ), the latched behaviour could be made optional.

If this is meant to provide the latched behavior, we should make it a latched behavior...i.e. if latched is desired, then it should hold the last message forever...

You could also add a lazy behavior that only publishes the throttled topic in case there is a subscriber using the [getNumSubscribers](http://docs.ros.org/api/roscpp/html/classros_1_1Publisher.html#ad56c8e954020290dcb87cd6bbd330a2b) function

2017-07-03 18:49 UTC, fmessmer requested changes

2017-07-03 18:49 UTC, ipa-fxm commented on generic_throttle/package.xml
> +  <build_depend>rospy</build_depend>
remove ```<build_depend>rospy</build_depend>```

2017-07-03 18:51 UTC, MattiaRacca commented on generic_throttle/package.xml
> +  <build_depend>rospy</build_depend>
Ouch, I missed that one...

2017-07-03 19:07 UTC, MattiaRacca commented
> If this is meant to provide the latched behavior, we should make it a latched behavior...i.e. if latched is desired, then it should hold the last message forever...

We can do that by default the throttle latches the last message forever and, if the delay parameter is given, it behaves like the current code (drop after "delay" seconds). How does it sounds?

> You could also add a lazy behavior that only publishes the throttled topic in case there is a subscriber using the getNumSubscribers function

Sure, that's easy. I'll do tomorrow.

2017-07-03 19:18 UTC, fmessmer commented
> We can do that by default the throttle latches the last message forever and, if the delay parameter is given, it behaves like the current code (drop after "delay" seconds). How does it sounds?

I don't see a use-case for `delay`....
I'd just go with a boolean parameter `latched` which stores the last message forever or not at all...

2017-07-04 09:00 UTC, fmessmer requested changes
more detailed review...

I also have a suggestion for the parameter layout (this is pseudo-yaml using a list of topics with a dictionary for each topic item :wink:)
```
topics:
 - topic_name_1: {latched: False, lazy: True, topic_rate: 1.0}
 - topic_name_2: {latched: True, lazy: False, topic_rate: 42.0}
```

This way, you could specify ```latched, lazy, and frame_rate``` for each topic individually...you could then also assume all to be mandatory

I'd remove the ```namespace``` parameter and simply concatenate topic_name with ```_throttled``` suffix

2017-07-04 09:00 UTC, ipa-fxm commented on generic_throttle/README.md
> +Class GenericThrottle runs a ROS node which subscribes to a list of topics and
~~Am I missing something: there is no node that actually uses the GenericThrottle python module...
Are you going to add one? Where/How are you currently using this package/node?~~

Found the ```rospy.init_node```.
But still there is now ```__main__```/executable, right?

I'd rather have an executable python ```generic_throttle_node.py``` which makes use of ```generic_throttle.GenericThrottle``` class but does all the "node initialization" and spinning...

2017-07-04 09:00 UTC, ipa-fxm commented on LICENSE
> +                    GNU GENERAL PUBLIC LICENSE
Do you have a specific interest in adding the LICENSE explicitly?
We normally do not do this for our packages...

2017-07-04 09:00 UTC, ipa-fxm commented on generic_throttle/README.md
> +new messages become available, the throttle will start to publish again.
Please update the README and describe an example yaml layout, i.e. mandatory and optional parameters

2017-07-04 09:00 UTC, ipa-fxm commented on generic_throttle/src/generic_throttle/generic_throttle.py
> +        rospy.on_shutdown(self._shutdown)
see above: please move into an executable ```generic_throttle_node.py``` script

2017-07-04 09:00 UTC, ipa-fxm commented on generic_throttle/src/generic_throttle/generic_throttle.py
> +            parameter_string = '/generic_throttle/' + parameter_name
do not assume absolute namespace....just look for ```parameter_name``` under the node's namespace, i.e. ```parameter_string = parameter_name``` (of course then ```parameter_string``` is obsolete!)

2017-07-04 09:00 UTC, ipa-fxm commented on generic_throttle/src/generic_throttle/generic_throttle.py
> +            parameter_string = '/generic_throttle/' + parameter_name
do not assume absolute namespace....just look for ```parameter_name``` under the node's namespace, i.e. ```parameter_string = parameter_name``` (of course then ```parameter_string``` is obsolete!)

2017-07-04 09:00 UTC, ipa-fxm commented on generic_throttle/src/generic_throttle/generic_throttle.py
> +        parameter_list = ['namespace', 'topic_framerate']
I guess ```topic_name``` is better than ```namespace```

2017-07-04 09:00 UTC, ipa-fxm commented on generic_throttle/src/generic_throttle/generic_throttle.py
> +        rospy.spin()
move the spinning to the executable node

2017-07-04 09:00 UTC, ipa-fxm commented on generic_throttle/src/generic_throttle/generic_throttle.py
> +                                    topic_info[0], queue_size=1)
simply use the ```latched``` option of the Publisher constructor (see http://docs.ros.org/api/rospy/html/rospy.topics.Publisher-class.html#__init__) for achieving the latched behavior....no need to save the last message yourself....

2017-07-04 10:00 UTC, MattiaRacca commented on LICENSE
> +                    GNU GENERAL PUBLIC LICENSE
Actually there is no need and this should not be there, I'll remove it.

2017-07-04 10:08 UTC, MattiaRacca commented
Thanks, working on it.
> I'd remove the namespace parameter and simply concatenate topic_name with _throttled suffix
What if 2 throttles subscribe to the same topic? they would try to publish on the same _throttled topic, not respecting the specifications on rate.

I would actually put in front of the original topic name the namespace of the throttle node
```
/throttle1/throttle <--- this is the node for the first throttle in its namespace
/throttle1/camera/image_raw <--- throttled topic by the first throttle
/throttle2/throttle <--- second throttle in its namespace
/throttle2/camera/image_raw <--- throttled topic by the second throttle
```

2017-07-04 10:19 UTC, ipa-fxm commented
From the subscriber-perspective, it is counter intuitive to have the node name of the throttler in the topic name...the subscriber actually should not care about who is going to provide him with the throttled topic...he is just interested in being able to subscribe to the topic he is interested in but with a throttled frequency...thus topic_name + ```_throttled```-suffix....

2017-07-04 12:06 UTC, MattiaRacca commented on generic_throttle/src/generic_throttle/generic_throttle.py
> +                                    topic_info[0], queue_size=1)
If I use the `latch = True`, the publisher will yes keep the last message latched but a new subscriber to the throttled topic will receive **only once** the message and not at the rate specified in the throttle parameters.
Could this be fine?

2017-07-04 14:12 UTC, fmessmer requested changes
few minor requests....and then I would like to ask @ipa-fmw to verify the behavior for the intended use-case....

2017-07-04 14:12 UTC, ipa-fxm commented on generic_throttle/package.xml
> +  <maintainer email="mattia.racca@aalto.fi">Mattia Racca</maintainer>
I guess we should add someone from IPA as a maintainer, too, as it lives in the ipa320 organization...

2017-07-04 14:12 UTC, ipa-fxm commented on generic_throttle/CMakeLists.txt
> +catkin_package()
please add install tags for the executable node

2017-07-04 14:12 UTC, ipa-fxm commented on generic_throttle/src/generic_throttle_node.py
> +#!/usr/bin/python
I think the generic_throttle_node.py should node be within the src folder - which is reserved for the python module...
put it under generic_throttle/scripts

2017-07-05 08:55 UTC, MattiaRacca commented on generic_throttle/package.xml
> +  <maintainer email="mattia.racca@aalto.fi">Mattia Racca</maintainer>
I agree. @ipa-fxm  or @ipa-fmw?

2017-07-10 10:04 UTC, floweisshardt approved these changes

2017-07-10 10:04 UTC, ipa-fmw commented
@MattiaRacca adressed all comments from @ipa-fxm, so good to merge

2017-07-10 10:04 UTC, merged