Feature/resolution throttle
4am-robotics/cob_command_tools pull request #194
Opened 2017-07-10 11:12 UTC by MattiaRacca

Addition to generic throttle:
For sensor_msgs/Image you can define a resolution reduction and this will be applied before throttling. See README.md for more details.

2017-07-13 08:24 UTC, floweisshardt requested changes

2017-07-13 08:24 UTC, ipa-fmw commented on generic_throttle/README.md
> +    - /image_topic: {latched: False, lazy: True, topic_rate: 20.0, resolution: 2}
I would call this ```resolution_factor```

2017-07-13 08:24 UTC, ipa-fmw commented on generic_throttle/README.md
> +- `resolution`: it is meant for topics of type sensor_msgs/Image. If available, the throttle will reduce the resolution of the image by the specified factor. For example, if `resolution: 2`, width an
```resolution_factor```

2017-07-13 08:24 UTC, ipa-fmw commented on generic_throttle/package.xml
> +  <exec_depend>cv_bridge</exec_depend>
missing exec depend to ```rostopic```

2017-07-13 08:28 UTC, ipa-fxm commented on generic_throttle/src/generic_throttle/generic_throttle.py
> +                rospy.logwarn('Resolution option is not available for ' +
we dont want to see this warning for every non-image message comming in...

2017-07-13 08:59 UTC, MattiaRacca commented on generic_throttle/src/generic_throttle/generic_throttle.py
> +                rospy.logwarn('Resolution option is not available for ' +
If the user specifies the resolution_factor option for a non-image message, the throttle will throw the warning only once when the first non-image message comes through (as the resolution option for that non-image topic will be set to `None` - line 131 - and the `rospy.logwarn` statement will not be reached any longer).

2017-07-13 09:20 UTC, fmessmer requested changes

2017-07-13 09:20 UTC, ipa-fxm commented on generic_throttle/src/generic_throttle/generic_throttle.py
> +        factor = 1.0 / resolution
if the parameter is now called factor already then there should not be another 1/factor...it makes it confusing...
if you want the resolution to be halfed...you should set the resolution_factor param to 0.5 in the yaml...and not to 2!

2017-07-13 09:22 UTC, ipa-fxm commented on generic_throttle/src/generic_throttle/generic_throttle.py
> +        factor = 1.0 / resolution
also we need a division by 0 handling?

2017-07-13 19:26 UTC, fmessmer approved these changes
thanks @MattiaRacca for the contribution

I leave this to @ipa-fmw for final testing and merging

2017-07-17 13:05 UTC, floweisshardt approved these changes

2017-07-17 13:06 UTC, merged