[WIP] enhance ntp_monitor
4am-robotics/cob_command_tools pull request #200
Opened 2017-08-03 17:03 UTC by ipa-fxm

required for https://github.com/ipa320/cob_robots/pull/698

 - [ ]  made ntp_monitor configurable via yaml
 - [ ] ros.Timer for diagnostics publishing at 1 Hz
 - [ ] ros.Timer for querying `ntpdate -q`
 - [ ] enable/disable self-offset

2017-08-08 07:20 UTC, floweisshardt requested changes

2017-08-08 07:20 UTC, ipa-fmw commented on cob_monitoring/src/ntp_monitor.py
> +        print('NTP monitor is unable to initialize node. Master may not be running.', file=sys.stderr)
is this really neccessary? I think we can assume that a roscore is already running as we do for all other nodes.

And in that case I'd like to use rospy.logerr/warn/info/debug for all print output.

2017-08-08 14:45 UTC, ipa-fxm commented
@ipa-fmw ready to merge!

2017-08-10 09:32 UTC, ipa-bnm commented
@ipa-fxm you could consider using https://pypi.python.org/pypi/ntplib.

2017-08-11 11:44 UTC, floweisshardt approved these changes

2017-09-05 17:27 UTC, merged