enable setting textsize for visualization of navigation goals
4am-robotics/cob_command_tools pull request #217
Opened 2018-02-14 15:08 UTC by HannesBachter

- fixes nothing
 - no new source code files added

2018-02-14 15:49 UTC, floweisshardt requested changes
better solution to temporarily enlarge the textsize is to use dynamic reconfigure. This way we do not need to touch the bringup structure or kill/restart

2018-02-19 19:03 UTC, ipa-fxm commented
:+1: for dynamic_reconfigure

2018-02-23 12:55 UTC, ipa-fxm commented
tested with navgoal_teacher...works like a charm...
@HannesBachter @ipa-fmw

2018-02-28 11:28 UTC, floweisshardt approved these changes

2018-03-02 11:42 UTC, merged