add ping_computers monitor
4am-robotics/cob_command_tools pull request #234
Opened 2018-10-27 08:43 UTC by HannesBachter

- fixes part of https://github.com/mojin-robotics/cob4/issues/875 
 - new source code files added (proper [APACHE license header](https://github.com/ipa320/setup/tree/master/templates) **must** be used)

2018-10-29 20:03 UTC, HannesBachter commented
added functionality to be run on a local pc, specifying various subnets  and publishing a designated topic

2018-10-31 08:20 UTC, fmessmer requested changes
first quick review...I guess we haven't thought through the whole usecase yet

while we might want to use both variants (locally, remotely), I'm not sure this should be done from the same script

the robowatch version, might need 
 - to monitor several robots
 - to publish to several `slack` channels respectively (could be achieved by using the [`zmq_push`](https://github.com/mojin-robotics/mojin_tools/blob/kinetic-devel/slack/scripts/zmq_push.sh) mechanism)
 - to run without ROS (in order to detect PC failures without ROS running on the robot)

2018-10-31 08:20 UTC, fmessmer commented on cob_monitoring/src/ping_computers.py
> +            ip_prefix = ".".join(subprocess.check_output(['hostname', '-I']).split(".")[:-1])
I guess with this, the script could detect itself whether it runs locally (on robot) or remote (robowatch) - no need for the extra parameter `host_pc`

2018-10-31 08:20 UTC, fmessmer commented on cob_monitoring/src/ping_computers.py
> +                host_ip = ip_prefix+"."+str(host)
I think `hosts` should contain the full IP we want to ping - again, this helps combining local/remote variants without if-else-mechanism

2018-10-31 08:20 UTC, fmessmer commented on cob_monitoring/src/ping_computers.py
> +            self.diagnostics_publisher = rospy.Publisher('/diagnostics', DiagnosticStatus,queue_size=1)
the topic type of `/diagnostics` is 
```
rostopic info /diagnostics
Type: diagnostic_msgs/DiagnosticArray
```

2018-10-31 08:20 UTC, fmessmer commented on cob_monitoring/src/ping_computers.py
> +        return subprocess.call(command) == 0
I guess we could get more information out of this and not just true/false, e.g. 
```
ping -c 1 10.4.2.1
PING 10.4.2.1 (10.4.2.1) 56(84) bytes of data.
64 bytes from 10.4.2.1: icmp_seq=1 ttl=63 time=25.2 ms

--- 10.4.2.1 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 25.239/25.239/25.239/0.000 ms
```
if you parse the response of the `subprocess call` then we could put metrics such as package loss and delay into diagnostics

just create one DiagnosticStatus for each pc and append them to `DiagnosticArray`

2018-10-31 08:20 UTC, fmessmer commented on cob_monitoring/src/ping_computers.py
> +            rospy.Timer(rospy.Duration(1.0/diagnostics_frequency), self.publish_slack)
no need for an extra timer...just call publish from `publish_diagnostics` - this also remove duplicate code in both functions

2018-10-31 08:22 UTC, HannesBachter commented on cob_monitoring/src/ping_computers.py
> +                host_ip = ip_prefix+"."+str(host)
I realized, that when we have the whole IP for the hosts in the .yaml file - we cannot symlink them but have to add a separate .yaml file for each robot

2018-10-31 08:26 UTC, HannesBachter commented on cob_monitoring/src/ping_computers.py
> +            rospy.Timer(rospy.Duration(1.0/diagnostics_frequency), self.publish_slack)
in that case, we would publish the slack message every second, which would spam our channels - I don't know if we want that info being published so frequently

2018-10-31 08:29 UTC, fmessmer commented on cob_monitoring/src/ping_computers.py
> +            rospy.Timer(rospy.Duration(1.0/diagnostics_frequency), self.publish_slack)
only publish on error, then stop until ok again

2018-10-31 08:30 UTC, fmessmer commented on cob_monitoring/src/ping_computers.py
> +            rospy.Timer(rospy.Duration(1.0/diagnostics_frequency), self.publish_slack)
also, if we split the two variants, then "local" can publish diagnostics and "remote" would `zmq_push`

2018-11-02 09:05 UTC, fmessmer commented on cob_monitoring/src/ping_computers.py
> +        all_pingable = True
https://docs.python.org/2/library/functions.html#all could be used for this

2024-02-15 09:10 UTC, fmessmer commented
not planned

2024-02-15 09:10 UTC, closed without merging