combine auto_init and auto_recover
4am-robotics/cob_command_tools pull request #309
Opened 2022-01-05 10:45 UTC by pgehring

ref https://github.com/mojin-robotics/cob4/issues/2060

Combines `auto_init` and `auto_recover` into a new `auto_tools` node.

- [x] tested on mrk-5

2022-01-05 16:43 UTC, benmaidel requested changes

2022-01-05 16:43 UTC, benmaidel commented on cob_helper_tools/src/cob_auto_tools/auto_recover.py
> +    self.subscribe()
no need to enable re-subscribe if already enabled. check if already enabled/subscribed

2022-01-05 16:43 UTC, benmaidel commented on cob_helper_tools/src/cob_auto_tools/auto_recover.py
> +    return TriggerResponse(True, "auto recover disabled")
no need to disable re-unsubscribe if already enabled. check if already disable/unsubscribed

2022-01-10 08:39 UTC, fmessmer approved these changes

2022-01-10 08:39 UTC, merged