[WIP] fix netdata queries
4am-robotics/cob_command_tools pull request #326
Opened 2022-11-25 15:03 UTC by fmessmer

- [ ] add failing netdata queries into error log
- [ ] fix failing queries

2022-11-25 15:04 UTC, fmessmer commented
currently the following query fails:
```
[ERROR] [1669388593.760164]: /cpu_monitor_b1_201662_3957855067133744992_b1(query_netdata): NetData request not successful (url: 'http://127.0.0.1:19999/api/v1/data?chart=sensors.coretemp_isa_0000_temperature&format=json&after=-5', status_code 404
```

2022-11-28 13:49 UTC, pgehring requested changes
failing queries fixed in https://github.com/fmessmer/cob_command_tools/pull/5

2022-11-29 13:06 UTC, fmessmer reviewed
@pgehring can you finalize this?

2022-11-29 13:06 UTC, fmessmer commented on cob_monitoring/src/cpu_monitor.py
> +                    netdata_core_temp, error = query_netdata(name, interval)
please apply the try-execpt-logic to all usages of `query_netdata` and `query_netdata_info`

2022-11-29 16:29 UTC, pgehring requested changes
https://github.com/fmessmer/cob_command_tools/pull/6

2022-12-02 09:50 UTC, merged