extend battery_monitor with additional rosparams
4am-robotics/cob_command_tools pull request #333
Opened 2023-07-18 14:35 UTC by benmaidel

Added rosparams for:
- color_charging
- color_warning
- color_error
- color_critical
- interval_duration_warning
- interval_duration_error
- interval_duration_critical

The default values for the rosparams are the same as before. So if the new parameters are not on the parameter server loaded the behavior of this node should be the same as before.

2023-07-18 15:57 UTC, benmaidel commented
tested on mrl-5 :heavy_check_mark:

2023-07-18 16:48 UTC, fmessmer requested changes

2023-07-18 16:48 UTC, fmessmer commented on cob_monitoring/src/battery_monitor.py
> +        self.interval_duration_critical = rospy.get_param("~interval_duration_critical", 30.0)
this was previously set to `5.0`

2023-07-18 16:48 UTC, fmessmer commented on cob_monitoring/src/battery_monitor.py
> +        self.interval_duration_error = rospy.get_param("~interval_duration_error", 30.0)
this was previously set to `15.0`

2023-07-19 16:28 UTC, benmaidel commented on cob_monitoring/src/battery_monitor.py
> +        self.interval_duration_critical = rospy.get_param("~interval_duration_critical", 30.0)
copy past, nice catch

2023-07-19 16:28 UTC, benmaidel commented on cob_monitoring/src/battery_monitor.py
> +        self.interval_duration_error = rospy.get_param("~interval_duration_error", 30.0)
copy past, nice catch

2023-07-20 08:36 UTC, fmessmer approved these changes

2023-07-20 08:36 UTC, merged