Support New Netdata Swap Chart Name
4am-robotics/cob_command_tools pull request #338
Opened 2024-01-12 17:56 UTC by Deleh

The swap chart was renamed from `system.swap` to `mem.swap`. Both tables are queried now in the same manner as the CPU core temperatures, ref
- https://github.com/ipa320/cob_command_tools/pull/321

2024-01-18 09:05 UTC, schmid-jn requested changes
![image](https://github.com/ipa320/cob_command_tools/assets/136321028/25399b48-6c2f-44ba-9f4c-2ef05e4af65e)

Still some issues with NetData Diagnostic. Detected on mrl-7.

2024-01-18 10:37 UTC, fmessmer commented
would it make sense to also add a new KeyValue to the diagnostics which gives us the `netdata` version installed on the system?

2024-01-18 10:55 UTC, Deleh commented
> would it make sense to also add a new KeyValue to the diagnostics which gives us the `netdata` version installed on the system? most `netdata` diagnostic issues where related to a new/different `netdata` version...

Yes, good idea :+1:

2024-01-18 12:00 UTC, Deleh commented
> ![image](https://private-user-images.githubusercontent.com/136321028/297683506-25399b48-6c2f-44ba-9f4c-2ef05e4af65e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1NzIzMjAsIm5iZiI6MTcwNTU3MjAyMCwicGF0aCI6Ii8xMzYzMjEwMjgvMjk3NjgzNTA2LTI1Mzk5YjQ4LTZjMmYtNDRiYS05ZjRjLTJlZjA1ZTRhZjY1ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExOFQxMDAwMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mOTg4Njk1YzNkMzljNzA0NzY2ZDViOThkZTcyZWQ4YzQ5MTBmOTQ0YjdmNTI5MDRhMGMzZjkyMWFhNzBiZTdmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.toTve0-wU0x9bmrZXJkRlKqgHHfEXhDCZ9T0eMt_nxw)
> 
> Still some issues with NetData Diagnostic. Detected on mrl-7.

This happens only on `mrl-7` which has indeed a different (and newer) netdata version than `mrl-8`. I'll have a look how to fix this, those `cpu.cpu*` tables seem to have gone completely.

2024-01-18 13:32 UTC, Deleh commented
This seems to be an issue with netdata itself. The relevant CPU data isn't even shown in the web interface.

__How it is__
![image](https://github.com/ipa320/cob_command_tools/assets/7513730/6881869a-882a-4a6e-b55d-0fcaab534016)

__How it should be__
![image](https://github.com/ipa320/cob_command_tools/assets/7513730/ec22cdc3-3774-435e-b8c0-624131249a72)

Let's try a reboot first.

2024-01-18 15:13 UTC, Deleh commented
> would it make sense to also add a new KeyValue to the diagnostics which gives us the `netdata` version installed on the system? most `netdata` diagnostic issues where related to a new/different `netdata` version...

I've added the netdata version as key-value pair to `CPU Info` for now.

2024-01-18 15:34 UTC, benmaidel commented
Are the changes backwards compatible with old netdata versions? If not we should not forget to update netdata on all robots (basf, afi)

2024-01-18 15:48 UTC, Deleh commented
> Are the changes backwards compatible with old netdata versions? If not we should not forget to update netdata on all robots (basf, afi)

The `swap` changes are backwards-compatible. The `version` was not included until now but is available on e.g. `mrl-2`.

2024-01-19 07:50 UTC, fmessmer reviewed
@Deleh while you are on it
could you have a look at the old PR #330 
if it contains something useful maybe integrate it into #338 
if not, please close #330

2024-01-19 09:29 UTC, Deleh commented
> @Deleh while you are on it could you have a look at the old PR #330 if it contains something useful maybe integrate it into #338 if not, please close #330

#330 was a workaround for the `mrk` statemachine when we had serious problems with netdata. Malformed data should be treated as error, not as warning. I'll close it but keep the branch if we run into problems again.

2024-01-22 12:38 UTC, schmid-jn commented
Tested also on mrl-8: 
![image](https://github.com/ipa320/cob_command_tools/assets/136321028/2b31b7d9-6916-4dc9-9e10-45d3e38969ba)
Looks god

2024-01-22 12:39 UTC, schmid-jn approved these changes
Looks good!

2024-01-22 14:27 UTC, merged